services:
  entrypoint: /tModLoader/Scripts/entrypoint.sh
  tml:
    container_name: tml
    restart: unless-stopped
    build:
      context: .
      args:
        # TML_VERSION: v2023.8.3.3
    # entrypoint: [ "/bin/bash" ] # Uncomment this line if you need to poke around in the container
    tty: true
    stdin_open: true
    ports:
      - 7785:7777
    volumes:
      - ./tModLoader:/home/tml/.local/share/Terraria/tModLoader
    environment:
        PUID: 1000
        PGID: 1000
      - WORLD=/home/tml/.local/share/Terraria/tModLoader/Worlds/Dumpster.wld
      - PASSWORD=fire
      - MOTD="05/16/2024"
